package frc.robot.autos;

public enum Autos {
  LEFT_DOUBLE_SWIPE,
  LEFT_SWIPE_CLIMB,
  DELAYED_LEFT_SWIPE_DEPOT,
  RIGHT_DOUBLE_SWIPE,
  RIGHT_SWIPE_CLIMB,
  BUMP_MIDDLE_DEPOT_CLIMB,
  HUB_MIDDLE_DEPOT_CLIMB,
  CHAOS
}
