package frc.robot.autos;

public enum Autos {
  MAIN,
  LEFT_CLIMB,
  LEFT_DEPOT,
  LEFT_DOUBLE_SWIPE,
  LEFT_DOUBLE_SWIPE_BUMP,
  RIGHT_CLIMB,
  RIGHT_DOUBLE_SWIPE,
  RIGHT_DOUBLE_SWIPE_BUMP,
  RIGHT_PASS,
  MIDDLE_DEPOT_CLIMB,
  MIDDLE_DEPOT_NEUTRAL,
  HUB_MIDDLE_DEPOT_CLIMB,
  CHAOS
}
